/**
 * placeholders — the BlurHash of every Unsplash photograph the fixture corpus references, per crop.
 *
 * GENERATED by `scripts/gen-mock-placeholders.ts`; do not edit by hand. Regenerate when a fixture
 * gains a photograph: `deno run -A scripts/gen-mock-placeholders.ts`.
 *
 * Every hash here was computed from the real picture at the crop the corpus uses, by the same
 * encoder the upload path runs (`apps/web/features/files/core/media/blurhash.ts`). A photograph
 * the host no longer serves has no entry, and `mockPlaceholder()` returns `undefined` for it —
 * an absence, never a plausible default. Keyed by the bare slug (`photoSlug()` normalises).
 */

/** The three crops a photograph is taken at. See the generator for what each fetches. */
export type PlaceholderCrop = "cover" | "square" | "face";

export const PLACEHOLDERS: Readonly<
	Record<string, Readonly<Partial<Record<PlaceholderCrop, string>>>>
> = {
	"1438761681033-6461ffad8d80": {
		cover: "MKGJ56tSL3xDQl_Ns:s8NGIA?vRiRPxtR*",
		face: "UYHCN6o~pyxY?woextbH.TV@s;fk%$t7xvWC",
		square: "UaH2yVbwY6$%?wt7xuR*.8RjV@t7*0t7x]Rk",
	},
	"1441974231531-c6227db76b6e": {
		cover: "MEBpI5-.0OE2E2?F-ospE3IpwNa#S2jst5",
		face: "UBDI,R~TE4j??Z~A-UNIrdR,NHWB58M}xYs.",
		square: "UBDI,R~TE4j??Z~A-UNIrdR,NHWB58M}xYs.",
	},
	"1449844908441-8829872d2607": {
		cover: "MRDli|~UxaIVD*b_WBofaeoInhM|Rjodoz",
		face: "UWECRf~V?H%MkrbbbIozslNGRiaxt6o#WCj[",
		square: "UWECRf~V?H%MkrbbbIozslNGRiaxt6o#WCj[",
	},
	"1451187580459-43490279c0fa": {
		cover: "M34B:[t5ITRkIVIURjafkCxa4mafxvt6xa",
		face: "U44o1lt6s+R*IUWARkj@4mWBbcs:-nt7xuWV",
		square: "U44o1lt6s+R*IUWARkj@4mWBbcs:-nt7xuWV",
	},
	"1454165804606-c3d57bc86b40": {
		cover: "MPIh?MDi8xx[RP%gkCIUV@t7EjadofjFWA",
		face: "UIJIU:4THsjF?^kWD%Rj9^WUt7bF_MxaIBbI",
		square: "UIJIU:4THsjF?^kWD%Rj9^WUt7bF_MxaIBbI",
	},
	"1455390582262-044cdead277a": {
		cover: "M5FiJV-qoH?b4p-p-:_3-:D%~p9FxtRPD%",
		face: "U6FYx*ah-.-oR5Rj~p%LxuIV%LM{adDjxuIV",
		square: "U6FYx*ah-.-oR5Rj~p%LxuIV%LM{adDjxuIV",
	},
	"1461749280684-dccba630e2f6": {
		cover: "M897U|~pIXRl%Mn#t5s;RlRjNGRkWBjst6",
		face: "U89jim~WIBnNjDxsxut7IpNHNHNHt8NINGof",
		square: "U89jim~WIBnNjDxsxut7IpNHNHNHt8NINGof",
	},
	"1466611653911-95081537e5b7": {
		cover: "MeFq2SxZEgjZs.NeayoebHWV10NbxYbHWC",
		face: "UiGGwlt6I;ayNeays.j[10R+xYj[=_kBR*jZ",
		square: "UiGGwlt6I;ayNeays.j[10R+xYj[=_kBR*jZ",
	},
	"1467232004584-a241de8bcf5d": {
		cover: "MMAAm=R+4ToINcXnxuVsIUs:8_oz%hV?Ri",
		face: "UTB::ENGIAM{T0%MRjM{8^o#x^jER4M{xutS",
		square: "UTB::ENGIAM{T0%MRjM{8^o#x^jER4M{xutS",
	},
	"1470071459604-3b5ec3a7fe05": {
		cover: "MXE3I^ItRPt7NH_4NLRQofR*o}t8kCa~ay",
		face: "UbEff?Iqn~WD_4NJaeWWozt7kCfk9as.bIoe",
		square: "UbEff?Iqn~WD_4NJaeWWozt7kCfk9as.bIoe",
	},
	"1472099645785-5658abf4ff4e": {
		cover: "MJI#rzkCNfaK4Tt8Rj9Fof-;4.jZ-pkDXS",
		face: "UPK-Reozys%1o#ay9FRj9aV@$3kC%gofxZay",
		square: "ULJH:dtR?ws9%MM{4nj@0KjY-UkW%Moes:WB",
	},
	"1486406146926-c627a92ad1ab": {
		cover: "MsF?LuM{M{xuWB_4tRIUt8ayt7xvRjRPt7",
		face: "U:G]E#M_Rjof_4j@RjofozxvRjj[ayt7j]WB",
		square: "U:G]E#M_Rjof_4j@RjofozxvRjj[ayt7j]WB",
	},
	"1487014679447-9f8336841d58": {
		cover: "MOGS7LIVI=xuV?00%LM|RQxt-;ozIUt7M|",
		face: "UNG+ExIUNyxu4T%LIpIV_3WCj[xu59t7rpM{",
		square: "UNG+ExIUNyxu4T%LIpIV_3WCj[xu59t7rpM{",
	},
	"1487412720507-e7ab37603c6f": {
		cover: "MUI=Gg%g?wnNV@00WA9Fa}WB9GM{R5S5tR",
		face: "USGuXkpJt-%1J8xDV?RjNyV@wING~Wt7%Ms:",
		square: "ULH.7^.9?^$x9FMx9FIo9ZROMcNd^,WA%2WU",
	},
	"1489424731084-a5d8b219a5bb": {
		cover: "MsI:d$R+0fjbxas,fRa#WVbGM|azt7oLjZ",
		face: "UnJiwvxa0yM|s.oLaeWCRjWVs;j[RQWBkCof",
		square: "UgH,hmNa0yjbRja#xZS2IoWV%2fPNHayt6j[",
	},
	"1494522855154-9297ac14b55f": {
		cover: "MYH_[F?HR5t7Rj?w_2jFR+ofx]%1xuNHoy",
		face: "UaIh$[-pV@kW.T^+V@S5t7%1bbNGbctRs:n%",
		square: "UaIh$[-pV@kW.T^+V@S5t7%1bbNGbctRs:n%",
	},
	"1494790108377-be9c29b29330": {
		cover: "MKF}7%?HC7Ef~B?]x[NHjZ={$%kCj=xaxu",
		face: "UFG*Ww-=C7o}*II.#+xa02MxrqNG9]ni4:M{",
		square: "USGQ;8%2K%Sg_MkWt7ofxtNaxZxaw|V[%2of",
	},
	"1497366216548-37526070297c": {
		cover: "M9D+}I00x_R%_NAJo}WCkCxu^%.8RPt7IU",
		face: "UCDcK^E1D%x]E,kWRjoz~VxuxuV@?bWUxuRj",
		square: "UCDcK^E1D%x]E,kWRjoz~VxuxuV@?bWUxuRj",
	},
	"1497366754035-f200968a6e72": {
		cover: "MHEVpU?w%g~qb_tlbbt7%MkCRiV?WBR*ad",
		face: "UBE2@7I;=|~qtmM{xax]Rjw[X8RPRj%2t7jE",
		square: "UBE2@7I;=|~qtmM{xax]Rjw[X8RPRj%2t7jE",
	},
	"1497366811353-6870744d04b2": {
		cover: "MTEMI3_NT0kCaejEt6xat7t79GRjxuxuxu",
		face: "UPEM5q_3S$aeMxWBjZae01IUn$t7xZR*WCkC",
		square: "UPEM5q_3S$aeMxWBjZae01IUn$t7xZR*WCkC",
	},
	"1498050108023-c5249f4df085": {
		cover: "MSKnrPM_s:IU00_3%MayWBog?bf6D%WAog",
		face: "USLXc1%M~qxu?b%Maxxu_3ofD%V@D*j]xva#",
		square: "USLXc1%L~qxu?b%Maxxu_3ofD%V@D*j]xva#",
	},
	"1499750310107-5fef28a66643": {
		cover: "MZHLC@_N9ZD$D%I:-o?btRRPbvt7xEof%M",
		face: "UoJHdd_Nxuxu9ZxF-;t8S4ayRPV@ozRjaxf6",
		square: "UoJHdd_Nxuxu9ZxF-;t8S4ayRPV@ozRjaxf6",
	},
	"1499951360447-b19be8fe80f5": {
		cover: "MfM7P}~pR4D*RP.TxtRkaijYs9M{WFR*ox",
		face: "UnMtEz~padM|.St5R-WCr=RjRmWAaeM|n%ad",
		square: "UnMtEz~padM|.St5R-WCr=RjRmWAaeM|n%ad",
	},
	"1500648767791-00dcc994a43e": {
		cover: "MGEV+}?bCT9urW~CaJK6Nw%3nha{RjjZt8",
		face: "UIF697-pCT9u-;ROSibH9uWX,:smT1WB%2of",
		square: "UKEV$=-qC8E2~CjEF3NbjERjM{jYfkofWBWB",
	},
	"1502920917128-1aa500764cbd": {
		cover: "MZPZu?ay~q-;D%xujubHj[WB~qt79FM{xu",
		face: "UmOp*~Rj_3xuxuj[a{j[~qxuD%RjoffjayWB",
		square: "UmOp*~Rj_3xuxuj[a{j[~qxuD%RjoffjayWB",
	},
	"1506729623306-b5a934d88b53": {
		cover: "MBI#+K~qWU-;oe9F%MWBt7RjM{t7WBt7az",
		face: "U8I#+K_3Rjxv00xukBofM{jZV[t7WXofNGof",
		square: "U8I#+K_3Rjxv00xukBofM{jZV[t7WXofNGof",
	},
	"1506794778202-cad84cf45f1d": {
		cover: "MI9P.nxa0zE2-o-Ut6E2I:xaxuj[WBWBW=",
		face: "UK9P+fxZ0zELoLj[R*ayELR*-VxaIpayxaof",
		square: "UJ9i}5xG0fEL=xt69uNGt7ayWBf6j[ayj[oL",
	},
	"1507003211169-0a1dd7228f2d": {
		cover: "MHHL9--o80ElmkDND$E2WB.8^+%NNKj[V?",
		face: "UHF~2Dxa80NG4TITaKt7PBx]-oay4:M{$zof",
		square: "UcI5DB%2FzSi8^MxS$R*%gozV@ofM{oftRWV",
	},
	"1507591064344-4c6ce005b128": {
		cover: "MYF?CLV@0KMxV@~WWA9FozRk%MxuMxW;R*",
		face: "UjJkWL%MS2Vs~WaKn$t8.9t7s.oz-;W;NGof",
		square: "UtIrHTozIVRj~paeM{og%gs:jEbH%gt7jtoL",
	},
	"1508214751196-bcfd4ca60f91": {
		cover: "MdHBxZ?GE0xubc~WxuRP%Mt7%gozs.xut7",
		face: "UmL4EBROxtWV_NM{ayWBtlRjWBWVxva}NGae",
		square: "UkI;;c%1In%M~qWBM{xuyDR*WARk%MWBaya#",
	},
	"1508614999368-9260051292e5": {
		cover: "MnOV}fxaRjofWB1Sa#a{W;fPR5bGafjZj[",
		face: "UsOfiFt6ayof1SahbFa}VrbGayf6ogjba{fj",
		square: "UsOfiFt6ayof1SahbFa}VrbGayf6ogjba{fj",
	},
	"1509391366360-2e959784a276": {
		cover: "MZC?_,IUfjt7of.AM{a}ofj[aJRkWCoeay",
		face: "UYC%XAIURjt8.AM{WBt7nzRjWDt7acM{a}of",
		square: "UYC%XAIURjt8.AM{WBt7nzRjWDt7acM{a}of",
	},
	"1512941937669-90a1b58e7e9c": {
		cover: "MDIFY#55tk~Vx]1J^k-;9uMd?GgOj]s*Ip",
		face: "UII5#*0eNFs85k^*%gSj?GXUs.t6.8OAR6Vr",
		square: "UII5#*0eNFs85k^*%gSj?GXUs.t6.8OAR6Vr",
	},
	"1515169067868-5387ec356754": {
		cover: "MIEBHL~A9^M|WB5rs:$%NaM|=tocR-$%t6",
		face: "UBELHE~o4;iw%gsARPI;?Gr?IoxY%1ELWAxZ",
		square: "UIFX9Z~BI;M|1O-U-nxG^NNbRkoLJ-bbbaf*",
	},
	"1516131206008-dd041a9764fd": {
		cover: "MGJIR=-mInE2xv4TM_WVD%IUs:8_WBjZR*",
		face: "UKJbXC-:M{E14T-:ozIAs-R*fPV@x[-;oLkC",
		square: "UKJbXC-:M{E14T-:ozIAs-R*fPV@x[-;oLkC",
	},
	"1517048676732-d65bc937f952": {
		cover: "MNHLMNI90Lx_Dh-:XUaJ%1%gE2r=xGWXx[",
		face: "UBA+,3-o=cIU}rxZs9IoofR*R-WDNHWXoLs:",
		square: "UNI;@wDgOaae%LI[I9og9ar;ROWB^*r=Sft7",
	},
	"1517245386807-bb43f82c33c4": {
		cover: "MMEx*LaL9ZS%Rj0e?GxvV@t79YE2%Ls,Ip",
		face: "UVBozJRj0e%3bbR%aexbIoof%2R%sSaxS4og",
		square: "URFYAcr=M|xu0K%MofWB9YEM%LjZ%MsSRjof",
	},
	"1517841905240-472988babdf9": {
		cover: "ME7pMyRj0fx^=?tPazSiflr=xubHRPkCtm",
		face: "UEBOBu0L21=wyYMwrVt-AIt8$ei^I9x]R*e:",
		square: "UB7DFNRj0Kx]koWXkrofS4kCr;V@TKWVxDoe",
	},
	"1518432031352-d6fc5c10da5a": {
		cover: "MGBg0r_N%Ls:M{xtxuR*RjoMjbxuR*V@of",
		face: "UDBM[M_N-:tQ%L-pW:V@RQtPRjV@-;xv%Mt6",
		square: "UDBM[M_N-:tQ%L-pW:V@RQtPRjV@-;xv%Mt6",
	},
	"1519003722824-194d4455a60c": {
		cover: "MdI5}E?bDONuV?UHtRrrtRV@ADIpt7o#oK",
		face: "UjI$m7-;Mys:P;ays:f+5RIof,fkRjW;X8WB",
		square: "UjI$m7-;Mys:P;ays:f+5RIof,fkRjW;X8WB",
	},
	"1519085360753-af0119f7cbe7": {
		cover: "M35h78xu9Z-p~W~C%2I:xZ^k-oxuI;t7-p",
		face: "UC840vs:0eM{jYWBkCs:9uR*-oxaM|oLxtWV",
		square: "U567+Yt756%2~Vt79txa-VofEMs:s:R*NGs:",
	},
	"1519389950473-47ba0277781c": {
		cover: "M7J8U~V?9#vfY6E,yEO[DiJppepyS%nlNy",
		face: "UEJkcZ-;IU}=NG.8n$RP%hyDX8a0yE%Mnh%1",
		square: "UEJkcZ-;IU}=NG.8n$RP%hyDX8a0yE%Mnh%1",
	},
	"1521119989659-a83eee488004": {
		cover: "MrLr0dWB?^x]IA_NoLR*kWV@emWBM{ogt7",
		face: "UtMt,K%M?^oz_3MxRkozRkxuMxjZ%ha}V@RP",
		square: "U$L=5zWB.8t8_NofNGkCoJaxM{aeWBj[jZjZ",
	},
	"1521737604893-d14cc237f11d": {
		cover: "MJEyJRD%M{Z$oz~pRjx]a0M{IURjt7x]Rj",
		face: "UOF$CZyXDi00-Ux^azITRkIUf5tRj?ogs:f+",
		square: "UHFFT=OYR5Vs~Vo#%gadD%Mxxa%NVrV?M{M{",
	},
	"1522071820081-009f0129c71c": {
		cover: "MCBWMXRkR*tRMx~Wt8bHozxt$yogkCt8fk",
		face: "UCB:a5V[x^-;~Vs:NH%M$xjYozt7-oRlozoz",
		square: "UCB:a5V[x^-;~Vs:NH%M$xjYozt7-oRlozoz",
	},
	"1522202176988-66273c2fd55f": {
		cover: "MJC$$M~q%M%1ogT0NHIoNGRjNat6t7kDR*",
		face: "U6BfnY?vs;~pL1t7M{E1yrx]ozbbx]9anh=|",
		square: "UCCPkh_N%LxB%$XSNHR+OE$*%2%N_3-;kWoe",
	},
	"1522542550221-31fd19575a2d": {
		cover: "MFM*BZIwpuH@n5yC-qXgRkIV~qD%Myx[sr",
		face: "UNNAuHTKpa4V%g%3x@n-_MMyM{-;%Lt7RQoe",
		square: "UNNAuHTKpa4V%g%3x@n-_MMyM{-;%Lt7RQoe",
	},
	"1523275335684-37898b6baf30": {
		cover: "M9Op#=?b~qxu9F-;xat7M{Rj?bV[9Fof?b",
		face: "U9OgHG?b~qt7%2xuofRj~WRj4nxu_3RjIU%M",
		square: "U9OgHG?b~qt7%2xuofRj~WRj4nxu_3RjIU%M",
	},
	"1524504388940-b1c1722653e1": {
		cover: "M99j7Y9a0~-ojG^jxa57I:=|$+oKNGNbxG",
		face: "UBAS=1E20zs:Ne$%NGWX0fof^jWUn%R*xajt",
		square: "U896]*E10~%2^k%157IpNHs:n$NHEMWV%1of",
	},
	"1524758631624-e2822e304c36": {
		cover: "MKLz{nZgRkx]M{~WDhtRi^ofpJ%gITWWMy",
		face: "UJM7osiHt8-:^+D%flMx.T%gWAg3bwkBnht8",
		square: "UJM7osiHt8-:^+D%flMx.T%gWAg3bwkBnht8",
	},
	"1527980965255-d3b416303d12": {
		cover: "MOJkJ?f,pYkC4m_4D%E1t79G57R$xHxuoz",
		face: "UrK^]Ut7x[xb~qRja}kBS$ofsCkB?Hxbj[ae",
		square: "UqJ*etoftQt7~qWBNGofXTocspt7-pxbs:ay",
	},
	"1531123897727-8f129e1688ce": {
		cover: "MBA]+^$#iyjEI99Do#V@xu?c_4WAWDM{IA",
		face: "U49?:wXQ8|t9MuI@D*D$.AIoxt-;8^WFRjaJ",
		square: "UGBy%5%2RRRO8^M|oI%N-=ozRlRPoMRjs.of",
	},
	"1531403009284-440f080d1e12": {
		cover: "MZJbN#DNE2xuEL?boykCWBWCozbwnhV@s:",
		face: "USKnuO8^f5bv_3t8ofR*XTo~RjaJa}RjRjsm",
		square: "USKnuO8^f5bv_3t8ofR*XTo~RjaJa}RjRjsm",
	},
	"1531427186611-ecfd6d936c79": {
		cover: "MUDv=#Di00-;r?Mcogo~WAxaVsogkDWBt7",
		face: "UIDJbS4n0f?b8^%MxaM{TLRi-VNGITt7WBj[",
		square: "UQC@1^Di4m-=ISt7tmRPMwoyxuWVx^aeaJWB",
	},
	"1534528741775-53994a69daeb": {
		cover: "MZGbx{t8-@$dIpn#WrawoLWYM]jtohbJt7",
		face: "UXFr-~WT%j-or:ogjXa~M]n$n$Ne%PogWBj]",
		square: "UfE{h;t8%PxB%Nj]j[f5DzjbadS6%OoJflWU",
	},
	"1544005313-94ddf0286df2": {
		cover: "MGAva+?G0#57sT,.ngE2I=kDtRt7oLe.R*",
		face: "UbFFQu-oS$NH~qt6xaof.8kDxZxFo#WBM|a}",
		square: "UKCidV?HK5EM~UxXtRNd?utQ-oxZ.7t7-:s.",
	},
	"1545235617-9465d2a55698": {
		cover: "MZIOnT01kqNGxF?bRmxuoeM{9ajF-pRiWq",
		face: "URI}^m01_4NZ%f%3ogIntS%M^+jXM_%LIUIU",
		square: "URI}^m01_4NZ%f%3ogIntS%M^+jXM_%LIUIU",
	},
	"1550684848-fac1c5b4e853": {
		cover: "MaN8p.Gw5tRhtJ=$=DxB$eRlIe$yjKR:jJ",
		face: "UdN[O8PX9+Ng-Y$L$y$fIw$wX7WY%1oxIvWU",
		square: "UdN[O8PX9+Ng-Y$L$y$fIw$wX7WY%1oxIvWU",
	},
	"1550745165-9bc0b252726f": {
		cover: "MPAS_+ExMa$*V?RhjFo#ogWUDzw|kYR,o#",
		face: "UaA]{{J7V=%3RhadogWVI7xFWqR%bxt8V@j=",
		square: "UaA]{{J7V=%3RhadogWVI7xFWqR%bxt8V@j=",
	},
	"1550859492-d5da9d8e45f3": {
		cover: "M^MZLB#7o}r=Ne1Qk7sSWAbaIxR:a2W=oc",
		face: "U~MY?Hw0xts,1Qk8nibEJFV{RlayxVWFS$jr",
		square: "U~MY?Hw0xts,1Qk8nibEJFV{RlayxVWFS$jr",
	},
	"1551288049-bebda4e38f71": {
		cover: "MRDJbU00?H9Z?b_3M{M{ogWB^+M{M{s:af",
		face: "UZBzUsMxM{XT~qInNFWC^+InNGVs_3IoNGWB",
		square: "UZBzUsMxM{XT~qInNFWC^+InNGVs_3IoNGWB",
	},
	"1552664730-d307ca884978": {
		cover: "MWLq5~tm4n-okV~qkCxubJj]^+xvxbs:t7",
		face: "UQM%l;T14ojD~qjXxsn*?at8aiadNMM{V?Ne",
		square: "UPM%o{I]8{i]~qoHt5e;?btRn,ocI[M_RjS5",
	},
	"1553456558-aff63285bdd1": {
		cover: "MOGRxQ.8x]WUIB-:RPi_s.NH4TIAD%tRxv",
		face: "UKGk]{%#xutl~pV@IU%MM{MyMxx]xctRNbtR",
		square: "UKGk]{%#xutl~pV@IU%MM{MyMxx]xctRNbtR",
	},
	"1556740738-b6a63e27c4df": {
		cover: "MWIXy@_NJ7xao2?HxuRjWqoz4:ROM{t7tR",
		face: "UYKAf[?v_NW.yCWUM{R5IUjYM{W-%#x^t7ni",
		square: "UNI#P$?vNaic^*xtM{Rj0KMxIUx]9Fs:R,xa",
	},
	"1556742049-0cfed4f6a45d": {
		cover: "MLKn9*-p01ivx]MxxuaKxvof~W9F-;WBM|",
		face: "UVJ@d#M{_N%ft7Rjofs:tQW=nhofSMkDsnn%",
		square: "UILzmk%h00n4ITV@juxv_2D%.7M{s:V@jFM{",
	},
	"1557682250-33bd709cbe85": {
		cover: "MWFyRY1$sUWYjuF2sVfQfRfQjufQfQfQfQ",
		face: "ULFCyV1isVWsAcsofQfRo2fQa|fQb0fQfQfR",
		square: "ULFCyV1isVWsAcsofQfRo2fQa|fQb0fQfQfR",
	},
	"1558655146-9f40138edfeb": {
		cover: "M69tDYLd_1Ext4${0{?apI%f.8-;kVxuof",
		face: "U8A0,g?]-.OrJj9[s*xu%h^kR*xuJC-VD%rr",
		square: "U8A0,g?]-.OrJj9[s*xu%h^kR*xuJC-VD%rr",
	},
	"1573496359142-b8d87734a5a2": {
		cover: "MeINN,qt~A$is9^Pr=ofkCNH$%f6NaX8NG",
		face: "UmMPK{q[=_-U~AxCaekWS4f6RlI?-oV?j[bI",
		square: "UcI:|2v1^jxG}=$MofWX$%kCIpShsmoej[WB",
	},
	"1579546929518-9e396f3cc809": {
		cover: "M_Nl.b*}qysAk8}OWER-baWXVuOEkUj@jZ",
		face: "U~Nc:6z?mpr]}OafWWfjR8ShbabHW-o0n*j@",
		square: "U~Nc:6z?mpr]}OafWWfjR8ShbabHW-o0n*j@",
	},
	"1592280771190-3e2e4d571952": {
		cover: "MsIOnYV@oco2ofkuWBofazof.Aj]WBa#j[",
		face: "UsIh,9jZaxs:Xqf6azfk.AofWVbHkqogaxof",
		square: "UsIh,9jZaxs:Xqf6azfk.AofWVbHkqogaxof",
	},
	"1600880292089-90a7e086ee0c": {
		cover: "MpNJg_009vI?V@x^RPR5kXozPBM{aLjYsm",
		face: "UZNTOI000#Iok=MxDigOlAx]VtnNRPoeNKV@",
		square: "UZNTOI000#Iok=MxDigOlAx]VtnNRPoeNKV@",
	},
	"1600880292203-757bb62b4baf": {
		cover: "MMMtBc00_39a.7^iVsS6M_jX?Go#E1.8kE",
		face: "UYM%fj=yR8I;}@MdR$t6WBs:X8NINGoyt6s;",
		square: "ULLX0wIBVu58^fnjNKIV~BITIn%gV[Z~tQR*",
	},
	"1611262588024-d12430b98920": {
		cover: "MC7cq7sl1rNg,^kBbGaejZj[AnWY=3skNs",
		face: "UC8Cz#s*1rNhX4a}nijY60WZ=Ms%NFa#s;fh",
		square: "UC8Cz#s*1rNhX4a}nijY60WZ=Ms%NFa#s;fh",
	},
	"1611974789855-9c2a0a7236a3": {
		cover: "M24nxyxV0KbbNsSj=|$y9tW;4nJC?a,:Ip",
		face: "U35h0_w[MxoLI]^Qs+NG0KAa?G$iJ}9aJB-o",
		square: "U35h0_w[MxoLI]^Qs+NG0KAa?G$iJ}9aJB-o",
	},
	"1614850523459-c2f4c699c52e": {
		cover: "MsDadNVU=hjIsnB.a3KNnkbHt6rtoeWEW:",
		face: "Ue9r}Tm~-DnjGERnK4WExawKs.n+W=S2bHWW",
		square: "Ue9r}Tm~-DnjGERnK4WExawKs.n+W=S2bHWW",
	},
	"1618005182384-a83a8bd57fbe": {
		cover: "MkH^=f.MI,rGnO{{;ek7X5jrJOsFxGbYX8",
		face: "UeHneA*FJ4nS{M+ubXWVAAnVwgX7E9EkX9nm",
		square: "UeHneA*FJ4nS{M+ubXWVAAnVwgX7E9EkX9nm",
	},
	"1620121692029-d088224ddc74": {
		cover: "MF55iMV|M[XAi?W7WPfmV-tARdW6s;okbg",
		face: "UK5}|=aLS7WEV:oiRhV-RdW5n_ofjwoij^oi",
		square: "UK5}|=aLS7WEV:oiRhV-RdW5n_ofjwoij^oi",
	},
	"1620641788421-7a1c342ea42e": {
		cover: "MD95%qEb1W,^#;NXxJadR$sq5~sA]rJOJ%",
		face: "UF9YTgEbAS,bNXxJW9WT1W$R=NE{wzS1oMsV",
		square: "UF9YTgEbAS,bNXxJW9WT1W$R=NE{wzS1oMsV",
	},
	"1626785774573-4b799315345d": {
		cover: "MHAcx.}s=L,[#SEvKOEdEKI:OtJ%I:NGNF",
		face: "U98qgW=|xv%2oWyDW,R$yGo|t7kYDNVXxasl",
		square: "U98qgW=|xv%2oWyDW,R$yGo|t7kYDNVXxasl",
	},
	"1633332755192-727a05c4013d": {
		cover: "MfN0rC%M_NWBi^^+WBkWa#M_4.oLt7ofxu",
		face: "UjNmNN%M?^RjkCV@xakCX9ofV?oe-;WBoLj[",
		square: "UnLgkYxu?vj]~WWBt7WC9GayjFofx]kCn%ay",
	},
	"1633356122544-f134324a6cee": {
		cover: "M555:[m**0R5RPTcwIT0r?f6icNanNkCtR",
		face: "U34oZjxV.SeSO8xtNasoQ-ELVYS$iJxvVYtS",
		square: "U34oZjxV.SeSO8xtNasoQ-ELVYS$iJxvVYtS",
	},
};
