/**
 * gen-mock-placeholders — regenerate `packages/backend/mocks/placeholders.ts`, the BlurHash table
 * for every Unsplash photograph the fixture corpus references.
 *
 *   deno run -A scripts/gen-mock-placeholders.ts
 *
 * ## Why a generated table and not a computed one
 *
 * The placeholder pipeline (`@projective/ui/display` `ProgressiveImage`) paints a picture's BlurHash
 * while its bytes travel, and the SSOT (`files/metadata.ts`) forbids inventing one: a hash that does
 * not come from the picture is a placeholder that is confidently wrong. The live path reads the hash
 * that upload-time extraction wrote to the row; the fixture corpus has no upload, so its hashes have
 * to be computed from the real photographs ONCE and committed. That is what this script does — it is
 * the fixture corpus's stand-in for the upload extractor, running the SAME encoder over the SAME
 * kind of downscaled sample (`SAMPLE_MAX_EDGE`, `componentsFor`).
 *
 * ## Three crops per photograph
 *
 * A hash describes a crop, and the corpus takes three of every photo: a landscape cover or
 * thumbnail (`mockCover`), a square crop (the discovery corpus's owner avatars), and a face-centred
 * square (`mockAvatar`). At four-by-three components the difference between a 16:10 and a 4:3 crop
 * is invisible; the difference between a landscape and a face crop is not, so all three are kept and
 * `mocks/assets.ts` picks by the crop it is building.
 *
 * ## Tooling, not workspace code
 *
 * This file lives outside every workspace member on purpose: it imports the APP's encoder (the
 * backend may not) and writes into the BACKEND's mocks (the app may not). A root script is the one
 * place both are reachable, and nothing imports it.
 */
import { walk } from "jsr:@std/fs@^1/walk";
import { decode } from "npm:jpeg-js@0.4.4";
import { componentsFor, encodeBlurHash } from "../apps/web/features/files/core/media/blurhash.ts";

// #region Config
const ROOTS = ["packages/backend", "apps/web"];
const OUT = "packages/backend/mocks/placeholders.ts";
const HOST = "https://images.unsplash.com";
/** The same bound the upload extractor samples at: enough for a 4x3 field, cheap to fetch. */
const SAMPLE_MAX_EDGE = 64;

/** The three crops the corpus takes of a photograph, and the query that fetches each. */
const CROPS = {
	cover: `fit=crop&w=${SAMPLE_MAX_EDGE}&h=${Math.round(SAMPLE_MAX_EDGE * 10 / 16)}`,
	square: `fit=crop&w=${SAMPLE_MAX_EDGE}&h=${SAMPLE_MAX_EDGE}`,
	face: `fit=facearea&facepad=3&w=${SAMPLE_MAX_EDGE}&h=${SAMPLE_MAX_EDGE}`,
} as const;
type Crop = keyof typeof CROPS;
// #endregion

// #region Collect the corpus
const SLUG = /(?:photo-)?(\d{10,13}-[0-9a-f]{12})/g;

async function collectSlugs(): Promise<string[]> {
	const slugs = new Set<string>();
	for (const root of ROOTS) {
		for await (const entry of walk(root, { exts: [".ts", ".tsx"], includeDirs: false })) {
			if (entry.path.endsWith(OUT.replaceAll("/", "\\")) || entry.path.endsWith(OUT)) continue;
			const text = await Deno.readTextFile(entry.path);
			for (const m of text.matchAll(SLUG)) slugs.add(m[1]);
		}
	}
	return [...slugs].sort();
}
// #endregion

// #region Fetch + encode
async function hashFor(slug: string, crop: Crop): Promise<string | null> {
	const url = `${HOST}/photo-${slug}?${CROPS[crop]}&q=60&fm=jpg`;
	const res = await fetch(url);
	if (!res.ok) {
		console.warn(`  ${slug} ${crop}: HTTP ${res.status}`);
		return null;
	}
	const bytes = new Uint8Array(await res.arrayBuffer());
	try {
		const { width, height, data } = decode(bytes, { useTArray: true });
		const rgba = new Uint8ClampedArray(data.buffer, data.byteOffset, data.byteLength);
		return encodeBlurHash(rgba, width, height, ...componentsFor(width, height));
	} catch (error) {
		console.warn(`  ${slug} ${crop}: ${error instanceof Error ? error.message : String(error)}`);
		return null;
	}
}
// #endregion

// #region Emit
function emit(table: Record<string, Partial<Record<Crop, string>>>): string {
	const lines = [
		"/**",
		" * placeholders — the BlurHash of every Unsplash photograph the fixture corpus references, per crop.",
		" *",
		" * GENERATED by `scripts/gen-mock-placeholders.ts`; do not edit by hand. Regenerate when a fixture",
		" * gains a photograph: `deno run -A scripts/gen-mock-placeholders.ts`.",
		" *",
		" * Every hash here was computed from the real picture at the crop the corpus uses, by the same",
		" * encoder the upload path runs (`apps/web/features/files/core/media/blurhash.ts`). A photograph",
		" * the host no longer serves has no entry, and `mockPlaceholder()` returns `undefined` for it —",
		" * an absence, never a plausible default. Keyed by the bare slug (`photoSlug()` normalises).",
		" */",
		"",
		"/** The three crops a photograph is taken at. See the generator for what each fetches. */",
		'export type PlaceholderCrop = "cover" | "square" | "face";',
		"",
		"export const PLACEHOLDERS: Readonly<Record<string, Readonly<Partial<Record<PlaceholderCrop, string>>>>> = {",
	];
	for (const slug of Object.keys(table).sort()) {
		const crops = table[slug];
		const parts = (Object.keys(crops) as Crop[]).sort().map((c) =>
			`${c}: ${JSON.stringify(crops[c])}`
		);
		if (parts.length === 0) continue;
		lines.push(`\t"${slug}": { ${parts.join(", ")} },`);
	}
	lines.push("};", "");
	return lines.join("\n");
}
// #endregion

// #region Main
const slugs = await collectSlugs();
console.log(`${slugs.length} photographs, ${Object.keys(CROPS).length} crops each`);
const table: Record<string, Partial<Record<Crop, string>>> = {};
let done = 0;
// A modest concurrency: the host is a CDN, but 250 parallel requests from one client is rude.
const queue = slugs.flatMap((slug) =>
	(Object.keys(CROPS) as Crop[]).map((crop) => ({ slug, crop }))
);
async function worker() {
	for (;;) {
		const job = queue.shift();
		if (!job) return;
		const hash = await hashFor(job.slug, job.crop);
		if (hash) (table[job.slug] ??= {})[job.crop] = hash;
		done++;
		if (done % 25 === 0) console.log(`  ${done} done`);
	}
}
await Promise.all(Array.from({ length: 6 }, worker));
await Deno.writeTextFile(OUT, emit(table));
console.log(`wrote ${OUT}: ${Object.keys(table).length} photographs with at least one hash`);
// #endregion
