/**
 * @projective/ui/feedback — shared types.
 *
 * Cross-cutting shapes consumed by more than one feedback component (the Messages stack and the
 * Toast overlay). Component-specific prop interfaces stay with their component.
 */
import type { VNode } from "preact";
import type { Severity } from "../../fields/types/mod.ts";

// #region Messages
/**
 * A single entry in a {@link Messages} stack. `summary` renders emphasised, `detail` as the
 * secondary line; when only one of them is supplied it renders alone. `life` (ms) auto-dismisses the
 * item; omit it (or set `0`) to require an explicit close via `closable`.
 */
export interface MessageItem {
	/** Stable identity — required so the stack can add/remove/animate the correct row. */
	id: string;
	severity?: Severity;
	summary?: string;
	detail?: string;
	/** Show a dismiss control (default `true`). */
	closable?: boolean;
	/** Auto-dismiss after this many ms; omitted/`0` = persists until closed. */
	life?: number;
	/** Override the default severity glyph. */
	icon?: VNode;
}
// #endregion

// #region Toast
/** Corner anchor for the {@link Toast} overlay — nine-point placement. */
export type ToastPosition =
	| "top-left"
	| "top-center"
	| "top-right"
	| "center-left"
	| "center"
	| "center-right"
	| "bottom-left"
	| "bottom-center"
	| "bottom-right";

/**
 * A single toast notification pushed via `useToast().show(...)`. `life` defaults to `3000`ms;
 * `sticky` disables auto-dismiss (and the countdown affordance) entirely.
 */
export interface ToastMessage {
	/** Stable identity, auto-generated by `useToast` when omitted from `show(...)`. */
	id: string;
	severity?: Severity;
	summary?: string;
	detail?: string;
	/** Auto-dismiss delay in ms (default `3000`). Ignored when `sticky`. */
	life?: number;
	/** Never auto-dismiss; the user must close it explicitly. */
	sticky?: boolean;
	/** Show a dismiss control (default `true`). */
	closable?: boolean;
	/** Override the default severity glyph. */
	icon?: VNode;
}
// #endregion
