ALTER TABLE comms.channel_files ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.device_tokens ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.dm_messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.dm_participants ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.dm_threads ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.message_attachments ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.notification_prefs ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.notifications ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.project_channel_participants ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.project_channels ENABLE ROW LEVEL SECURITY;

ALTER TABLE comms.project_messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE marketplace.service_blueprints ENABLE ROW LEVEL SECURITY;

ALTER TABLE ops.admin_users ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.business_profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.freelancer_profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.org_invitations ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.portfolios ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.profile_links ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.skills ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.team_members ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.team_roles ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.teams ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.user_bookmarks ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.user_emails ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.user_skills ENABLE ROW LEVEL SECURITY;

ALTER TABLE org.users_public ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.cohort_memberships ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.cohorts ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.maintenance_contracts ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.project_activity ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.project_attachments ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.project_participants ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.project_stages ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.projects ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.session_attendance ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.session_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.stage_assignments ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.stage_budget_rules ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.stage_open_seats ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.stage_revision_requests ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.stage_staffing_roles ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.stage_submissions ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.submission_files ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.tickets ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.ticket_workload_reports ENABLE ROW LEVEL SECURITY;

ALTER TABLE projects.waitlists ENABLE ROW LEVEL SECURITY;

ALTER TABLE finance.escrows ENABLE ROW LEVEL SECURITY;

ALTER TABLE finance.spending_limits ENABLE ROW LEVEL SECURITY;

ALTER TABLE finance.invoice_line_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE finance.contribution_agreements ENABLE ROW LEVEL SECURITY;

ALTER TABLE finance.payout_splits ENABLE ROW LEVEL SECURITY;

ALTER TABLE security.penalties ENABLE ROW LEVEL SECURITY;

ALTER TABLE security.platform_params ENABLE ROW LEVEL SECURITY;

ALTER TABLE reviews.entity_reviews ENABLE ROW LEVEL SECURITY;

ALTER TABLE search.profiles_index ENABLE ROW LEVEL SECURITY;

ALTER TABLE search.projects_index ENABLE ROW LEVEL SECURITY;

ALTER TABLE search.services_index ENABLE ROW LEVEL SECURITY;

ALTER TABLE search.user_affinity ENABLE ROW LEVEL SECURITY;

ALTER TABLE search.query_logs ENABLE ROW LEVEL SECURITY;